"use client";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SIVIE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  function handleLogout() {
    localStorage.removeItem("access");
    localStorage.removeItem("refresh");
    localStorage.removeItem("payload");
    console.log("logout completed");
  }
  return (
    <html lang="ko">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no"
        />
      </head>

      <body className="homepage is-preload">
        <div id="page-wrapper">
          {/* <!-- Header --> */}
          <div id="header-wrapper">
            <div id="header" className="container">
              {/* <!-- Nav --> */}
              <nav id="nav">
                <ul>
                  {/* <!-- 카테고리 추가해주시면 됩니다 --> */}
                  <li>
                    <a href="#">Category</a>
                  </li>
                  <li className="break">
                    <a href="#">Category</a>
                  </li>
                  {/* <!-- Logo --> */}
                  <li className="sh_logo">
                    <h1 id="logo">
                      <a href="/">SIVIE</a>
                    </h1>
                  </li>
                  <li>
                    <a href="#">Category</a>
                  </li>
                  <li>
                    <a href="#">Category</a>
                  </li>
                  {/* <!-- 비회원은 Login으로, Login 화면에서 signup 버튼 만들기 --> */}
                  <li className="sh_mypage">
                    <a href="#">MyPage</a>
                    <button onClick={handleLogout} type="submit" value="Submit">
                      Logout
                    </button>
                    <ul>
                      <li>
                        <a href="#">NO.1</a>
                      </li>
                      <li>
                        <a href="#">NO.2</a>
                      </li>
                      <li>
                        <a href="#">NO.3</a>
                      </li>
                      <li>
                        <a href="#">더보기</a>
                        <ul>
                          <li>
                            <a href="#">바니</a>
                          </li>
                          <li>
                            <a href="#">당근</a>
                          </li>
                          <li>
                            <a href="#">바니</a>
                          </li>
                          <li>
                            <a href="#">당근</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </nav>
            </div>
          </div>

          {children}
          {/* <!-- Footer --> */}
          <div id="footer-wrapper">
            <ul
              className="menu"
              style={{ display: "flex", justifyContent: "center" }}
            >
              <li>&copy; Untitled. All rights reserved.</li>
              <li>
                TEAM: <a href="#">SIVIE</a>
              </li>
            </ul>
          </div>
        </div>

        {/* <!-- Scripts --> */}
        {/* <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/jquery.dropotron.min.js"></script>
        <script src="assets/js/browser.min.js"></script>
        <script src="assets/js/breakpoints.min.js"></script>
        <script src="assets/js/util.js"></script>
        <script src="assets/js/main.js"></script> */}
      </body>
    </html>
  );
}
